name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. See error '...'
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Expected the summary to be spoken aloud
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Got an error message instead
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        - SumVox version: (run `sumvox --version`)
        - OS: (e.g., macOS 14.1, Ubuntu 22.04)
        - Rust version: (run `rustc --version`)
        - LLM provider: (e.g., Gemini, Claude)
        - TTS provider: (e.g., Google TTS, macOS say)
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please paste your config file (remove API keys!)
      placeholder: |
        {
          "version": "1.0.0",
          "llm": { ... }
        }
      render: json

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste relevant log output (run with `RUST_LOG=debug`)
      placeholder: Paste logs here
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have removed API keys from config/logs
          required: true
        - label: I have included all relevant information
          required: true
